### ISSUE TITLE
Mashup markers don't respect Post Status

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Google-Maps-Builder#167]
@mathetos commented on [Fri Mar 25 2016](https://github.com/WordImpress/Maps-Builder-Pro/issues/75)
## Scenario:
- You create a mashup from posts or a CPT
- You want to remove one marker from the map, so you put the post in Draft mode (makes sense)
- The marker stays and any links to that post in the infobubble now lead to a 404.
## Problem:

Most likely our mashup isn't checking for the post status before populating the markers. It should and the marker should be removed from the map if the post status changes.

**Comment by TobiasMalikowski** [comment]
@matheos this is exactly the bug I've told you in my support request, so no reason for you to add another issue.

**Comment by mathetos** [comment]
Perfect. Thanks for the confirmation @TobiasMalikowski

**Comment by TobiasMalikowski** [comment]
@mathetos Just wanted to create a pull request with a bug fix for this, then I mentioned there is no Github repository for the pro version. So I'll post the fix here since its a one liner. Is this the prevered way of submitting a bug fix for the pro version?

**File:** google-maps-builder-pro/includes/admin/mashups/class-mashups-builder.php
**Line 527:** (maybe the line is not on point, since I already have another fix (#249) in my file.
**WordPress Reference:**
 [https://codex.wordpress.org/Class_Reference/WP_Query#Status_Parameters](url)

**Original code:**
`
$args = array(
    'post_type' => $post_type,
    'posts_per_page' => - 1
);
`
**Code which fixes the issue:**
`
$args = array(
    'post_type' => $post_type,
    'post_status' => 'publish',
    'posts_per_page' => - 1
);
`
Please merge this into the next release. Thanks.

**Comment by nishitlangaliya** [comment]
@kevinwhoffman , This issue is fixed in https://github.com/WordImpress/Maps-Builder-Pro/issues/106
