### ISSUE TITLE
When "Signed-in Maps" settings is enabled site markers are non-clickable on map

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Google-Maps-Builder#168]
@sstruemph commented on [Wed Feb 17 2016](https://github.com/WordImpress/Maps-Builder-Pro/issues/47)

When "Signed-in Maps" is enabled in the settings the markers are no longer bringing up information in a popup when clicked.

A user reported this today. I was able to replicate the issue on my local site.

---

@Shelob9 commented on [Wed Feb 17 2016](https://github.com/WordImpress/Maps-Builder-Pro/issues/47#issuecomment-185419096)

@sstruemph Are you getting any JavaScript errors? I'm mid-refactor and am having issues with markers, assumed it was my fault. Would be useful to know if this was a pre-existing condition.

---

@sstruemph commented on [Wed Feb 17 2016](https://github.com/WordImpress/Maps-Builder-Pro/issues/47#issuecomment-185429662)

@Shelob9 No JavaScript errors.

---

@Shelob9 commented on [Wed Feb 17 2016](https://github.com/WordImpress/Maps-Builder-Pro/issues/47#issuecomment-185430006)

Ok, your bug is special and unique, we will need to recheck this until after I put refactor branch into testing.

---

@sstruemph commented on [Fri Mar 11 2016](https://github.com/WordImpress/Maps-Builder-Pro/issues/47#issuecomment-195538203)

@Shelob9 Do you have an update on this?

**Comment by sstruemph** [comment]
@mathetos A support ticket reported an issue where their markers were not clickable (the infobubble did not display when clicked). Their site has errors including this from Google:

**Google Maps API warning: SignedInDeprecated**

And according to the Google Docs:	
"The signed_in parameter is deprecated and will be ignored in future versions of the Google Maps JavaScript API. It won't prevent the Google Maps JavaScript API from working after signed-in mode has retired, but the behavior of your application may change, if you rely on current signed-in features.

Please review your application and see Signed-in Maps | Google Maps JavaScript API for details about the upcoming changes."

I wonder if this issue is back again because Google has deprecated the Signed-In feature. Also, we should consider removing that from the plugin if it's going away and especially if it's breaking this functionality with the infobubbles not opening when a marker is clicked.

**Comment by DevinWalker** [comment]
Closing in favor of https://github.com/WordImpress/Google-Maps-Builder/issues/275
