### ISSUE TITLE
Swap out qtip.js for hint.css

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Google-Maps-Builder#217]
We're ditching qtip.js on Give ([see here](https://github.com/WordImpress/Give/issues/619) ), I'd like to ditch it here as well, it breaks too easily and ends up breaking functionality across the plugin.

[Here's hint.css info](https://github.com/chinchang/hint.css)

I think our implementation in GMB is relatively simple so I don't anticipate any problems, just different markup really.

@lchski Do you anticipate any backward compatibility issues at all with this?

**Comment by lchski** [comment]
I don’t see what backward compatibility issues could arise; as long as all the markup is updated correctly, we should be fine.

**Comment by lchski** [comment]
I made progress towards this in [maps-builder-core/217-hint-css](https://github.com/WordImpress/maps-builder-core/tree/217-hint-css); it’ll need to be removed once the new InfoWindows are working. The JS-version could position itself relative to the windows fine, but the hint.css version was having a few clipping issues. I didn’t investigate further, though, because they’re contingent on having a finalized InfoWindow.

**Comment by DevinWalker** [comment]
This is too big of a change to hold up 2.1 - bumping
