### ISSUE TITLE
Support HTML like YouTube embedding in InfoBubbles

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Google-Maps-Builder#218]
Currently if you were to add a YouTube embed into a marker bubble, you would see it previewed correctly until you save the map. On refresh, and opening the marker, you'd see that the embed is removed.

Also, shortcodes do not render from inside the infobubbles at all.

Should we be supporting embeds and/or html in our infobubbles?

@DevinWalker What's your thought on this?

**Comment by vassilenkoff** [comment]
Thank you @mathetos. 

Hello @DevinWalker - I've contacted the Support page about this a week or so ago and have been keeping my fingers crossed since then - it hurts now so I though I would leave a message to see whether there is a chance of having HTML support in the Big Update that is coming up. I haven't seen any other plugin like yours and would love to stay with it but HTML support is crucial in my case.

**Comment by vassilenkoff** [comment]
This is inspiring @DevinWalker 
Looking forward to 2.1 - thank you for your work.

**Comment by vassilenkoff** [comment]
I can see that there is only this item left in the 2.1 milestone pipeline. Getting so excited.

**Comment by DevinWalker** [comment]
Hey @vassilenkoff are you attempting to place HTML or a shortcode within the info bubble?

**Comment by vassilenkoff** [comment]
Hey @DevinWalker I am attempting to embed YouTube videos which would be iframes.

**Comment by DevinWalker** [comment]
Cool that's what I figured. Good news! I got that working.

**Comment by vassilenkoff** [comment]
Fantastic news @DevinWalker!  Do you have any approximates on the date of the 2.1 launch?

**Comment by DevinWalker** [comment]
@vassilenkoff the goal is to wrap up testing this week and launch mid next week if all goes well.

**Comment by vassilenkoff** [comment]
Thank you @DevinWalker If you need any help with testing the HTML feature of the info bubbles please let me know.
