### ISSUE TITLE
Modal Sections

### ISSUE THREAD

**Issue by mathetos** [WordImpress/google-maps-builder#55]
Should the sections of the Modal builder be Accordion stlye, only allowing one to be open at a time?

**Comment by DevinWalker** [comment]
Probably yes...

**Comment by DevinWalker** [comment]
Users would get less confused. It's easy to open a ton of panels and get lost right now.

**Comment by kevinwhoffman** [comment]
My preference is to allow multiple vertical tabs to remain open if the user has already opened them. The interface has the potential to be very tall in terms of screen space when many markers are added, so allowing only one tab to be open at a time would cause the interface to jump drastically if a very tall section closed on click. It's possible that the tab you just clicked would even jump out of the viewport. Furthermore it adds more clicks to the overall experience.

I do agree that the interface in it's current state all kind of blurs together when multiple tabs are open because everything is white with no contrast between sections. This thread was the inspiration for my work in #66. See Figure 3 and let me know if that addresses your concerns here.

**Comment by DevinWalker** [comment]
I'm satisfied for not with @kevinwhoffman explanation and the work we've done with the UI. I haven't heard anyone complaining about the UI not working in accordion style since we've release 2.0.
