### ISSUE TITLE
Gathering Map Builder comments

### ISSUE THREAD

**Issue by paaljoachim** [WordImpress/google-maps-builder#75]
WOW guys I am very impressed the Map Builder is just awesome!

I will add the work fix to signal something to look at.

(FIX?)
Display Options
I changed the Map Size.
Width: 50% to see if the map in the builder changed to 50% of the screen but no change.
I thought it might auto change right away. 
(Again having a lock between the two would enable having a map ratio.)

I zoomed out using the mouse and dragged it over to Oslo, Norway then clicked to where I live but nothing happened.

Cool I changed the Map Type and it automatically updated!

(FIX)
Map Layers
Traffic Layer
Transit Layer
Bicycle Layer
Remove all the extra Layer words. One just needs it in the title Map Layers.

Map Theme
Interesting! Basically customize your map feature!
Very nice options here!

(FIX)
I clicked on Set a Custom Snazzy Map and the JSOn text box opened. I clicked the same button again but nothing happend. Click the button once to open and again to close.

Impressive how one can customize the Map Controls!
Looks good! Nice and straightforward!

(FIX - Drop a marker does not work. It seems you guys are working on this section...)
Map Markers
Drop a Marker does not work right now (you might have mentioned it in the mail.)
(AHHH! There is a Drop a Marker button on the bottom of the screen. I did not notice it before having gone through the options on the right.(
I added a location and a marker dropped into place.
The section seems a bit off not working fully so I will let it be for now....
As I tried adding multiple markers, but could only add one at a time.

Directions Display
No reaction. Not working yet it seems.

Google Places
Interesting! Very nice!

I read something in the email about Mashups not working yet. So this will will need to test later.

<b>Bottom options</b>
Add Location
A very think text line here. It feels like something is missing here. But can not put my finger on it yet.
A map showing the world?

Drop a Marker
Which switches over to Click on the Map
Then opens a map box to fill in a title and info.
There is even an icon one can switch out.
Clicking Change Icon opens Customize Map Marker. Very cool.

Goto Location
A very think text line here. It feels like something is missing here. But can not put my finger on it yet.
A map showing the world perhaps?

Edit Map Title
Map Title - thin line text box. I am not sure what this is about yet.
Perhaps it shows a drop down of existing maps? Right now I have not made a map yet.
Then one picks the one one wants to edit.....?

Set Lat/Lng: 
(View Lat/Lng?)
Turn on or off?

**Comment by mathetos** [comment]
Paal,

We really need each of these split into separate tickets since there most likely needs to be conversation around each point and we need to be able to resolve it with a committ (or Pull Request) or we need to close it. I'll do that though, as indicated below. Here's my response to those issues:

### Display Options ###
* No, the width/height is intended only for front-end presentation. You'll see it fill 50% of the content area when it's embedded on your page/post. You can also always click on the "Preview Map" button to see what it looks like on the front-end.

### Map Layers ###
* Good suggestion, making a new ticket

### Snazzy Map ###
* You have to go get the code from the SnazzyMaps website to insert into that field. That's why we provide the link there. Maybe there's better wording we can add there to make that more explicit

### Directions Display ###
* The Directions absolutely work, but they are intended for the front-end. So after you choose that, you'll see them on the front-end. So if you embed your map and you still don't see the diretions please create a NEW issue about that. 

### Goto Location ###
* Maybe a quick description above the field that says "Type a location here and choose it and your map will be re-centered over that location" -- Making a new ticket

### Edit Map Title ###
* Same suggestion as Goto Location, a quick description text will help this. -- Making a new ticket

**Comment by DevinWalker** [comment]
Thanks for splitting these up @mathetos

**Comment by paaljoachim** [comment]
Hey guys. I apologize for not splitting it up right away.
