### ISSUE TITLE
feat - Edit map - drag location marker

### ISSUE THREAD

**Issue by paaljoachim** [WordImpress/Google-Maps-Builder#77]
Edit map

Default drag the map.
Click and drag marker does not work.

**Comment by mathetos** [comment]
Correct. Dragging is not yet supported. Would be nice, but maybe not in this version.

**Comment by paaljoachim** [comment]
https://developers.google.com/maps/documentation/javascript/markers

Make a marker draggable

To allow users to drag a marker to a different location on the map, set draggable to true in the marker options.

var myLatlng = new google.maps.LatLng(-25.363882,131.044922);
var mapOptions = {
  zoom: 4,
  center: myLatlng
}
var map = new google.maps.Map(document.getElementById("map"), mapOptions);

// Place a draggable marker on the map
var marker = new google.maps.Marker({
    position: myLatlng,
    map: map,
    draggable:true,
    title:"Drag me!"
});

**Comment by DevinWalker** [comment]
Dragging isn't too hard to implement but we have to consider what happens when the dragging stops. We have to update the lat/lng obviously, but what if the marker was on a specific Google Place location prior? Should that place info be auto removed and the place ID field cleared. Also, once the dragging stops should we look for places in that area and see if the user meant to drop it on one?

**Comment by paaljoachim** [comment]
".....but what if the marker was on a specific Google Place location prior? "

If the place is already saved/added to the map. On drag a location bubble could show up: giving a warning message "Clear information from current map location?" Click yes or cancel. On cancel the marker till return to its last location. It will then alert the user that the current location was already added to the map. They will then have a choice of clearing the current location from the map or not.

" Also, once the dragging stops should we look for places in that area and see if the user meant to drop it on one?"

Are you saying if the marker is dropped very close to another marker what should then be done?
Can you explain this a bit for me.

**Comment by nishitlangaliya** [comment]
@DevinWalker ,

I have added code for make markers draggable while creating marker and for already added marker. I have prepared video for how it works.

https://www.useloom.com/share/25f63f4b085b4c48a71afdf39c112611

Regarding concern about drag and drop marker on same place.  I think admin will not place duplicate marker on same place because it will overlap on current marker.

Also even if we prevent to drop marker on same place on drag end event. still, admin is able to add same latitude and longitude from "Existing Markers" list. so by doing this if admin update map then two marker will display on same place overlapping on first marker.

Thanks.
