### ISSUE TITLE
feat(builder): add tooltips for marker fields

### ISSUE THREAD

**Issue by paaljoachim** [WordImpress/Google-Maps-Builder#89]
## User Story

As a user, I want to see tooltips for the marker fields so that I understand their purpose.

## Possible Solution

Using Hint.css, add tooltips to the following fields using the image below as reference

1. Marker Title - Defines the title of the infowindow.
2. Marker Description - Defines the description that appears below the title in the infowindow.
3. Marker Reference - @DevinWalker what is this field for?
4. Marker Place ID - Defines the Google Place ID of the marker if it is associated with a known Place.
5. Hide Place Details - Determines whether the Place details such as address, website, and phone number should appear in the infowindow.
6. Marker Latitude - Defines the latitudinal coordinates of the marker.
7. Marker Longitude - Defines the longitudinal coordinates of the marker.
8. Marker Infowindow - Determines whether the infowindow is opened or closed when the map first appears.

## Visuals

![image](https://user-images.githubusercontent.com/1938671/44556954-32e24000-a70a-11e8-86d6-257b0eeb49fa.png)

## Acceptance Criteria

- [ ] Each of the tooltips above appears as a question mark next to the field label. Text is displayed on hover.
- [ ] Any descriptions below the fields (crossed out in red) are removed favor of the new tooltips.

**Comment by nishitlangaliya** [comment]
@DevinWalker ,

As this issue was related to https://github.com/WordImpress/Google-Maps-Builder/issues/85. I had done the changes to https://github.com/WordImpress/Google-Maps-Builder/issues/89 ref #https://github.com/WordImpress/Maps-Builder-Core/pull/61/commits/f9aaaccf54e53385c4fc16d0a6579ae7a91f0445 and closing this issue in favor of https://github.com/WordImpress/Google-Maps-Builder/issues/85.

Thanks
