### ISSUE TITLE
Google image screen in a post or page

### ISSUE THREAD

**Issue by paaljoachim** [WordImpress/google-maps-builder#91]
In a page or post:
Is it possible to double click the Google map shortcode image used and it goes to the edit screen of the map used?

**Comment by mathetos** [comment]
That's a good suggestion. FooGallery does this really well and opens the "Gallery Edit" screen in a new tab.

**Comment by DevinWalker** [comment]
Double clicking on the shortcode opens the Maps Builder shortcode editor modal window so that the user can modify the map inserted. Perhaps we can add a link into the modal so the user can click to edit the map, but that's really a nice to have feature rather than critical. Closing this one out because I don't think it's necessary at this time.
